### PR TITLE
feed the hungry hungry caterpillar

### PR DESCRIPTION
**Pull request by ocefpaf**
@leewujung we could not get latest echopype b/c of the fsspec pin but will try to make it possible for projects to create environments and install it outside of the main env.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@abkfenris I'm playing with something locally that may help with the env creation. I'll repo back and add it here if it works.

**Comment by ocefpaf** [comment]
@abkfenris I can build this locally but here it is failing in https://github.com/oceanhackweek/jupyter-image/pull/38/checks?check_run_id=3243957509#step:5:1100

**Comment by abkfenris** [comment]
You could `USER root` and `USER jovyan` back afterwards.

**Comment by abkfenris** [comment]
It looks like when it clears the cache it's leaving it as root for some reason.

```sh
/srv/conda$ ls -lah
total 164K
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  2 17:43 .
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  1 19:12 ..
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  3 00:03 bin
drwxr-xr-x  2 jovyan jovyan 4.0K Aug  1 19:13 compiler_compat
drwxr-xr-x  2 jovyan jovyan 4.0K Aug  1 19:13 condabin
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  2 17:43 conda-meta
-rw-r--r--  1 jovyan jovyan   75 Aug  1 19:13 .condarc
drwxr-xr-x  3 jovyan jovyan 4.0K Aug  2 17:41 doc
drwxr-xr-x  2 jovyan jovyan 4.0K Aug  1 19:13 envs
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  2 17:42 etc
drwxr-xr-x  2 jovyan jovyan 4.0K Aug  2 17:41 fonts
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  2 17:43 lib
lrwxrwxrwx  1 jovyan jovyan    3 Aug  1 19:13 lib64.c~ -> lib
drwxr-xr-x  5 jovyan jovyan 4.0K Aug  2 17:42 libexec
-rw-rw-r--  1 jovyan jovyan  18K May 25  2019 LICENSE
-rw-r--r--  1 jovyan jovyan 2.5K Jul 25 07:44 LICENSE.txt
drwxr-xr-x  4 jovyan jovyan 4.0K Aug  2 17:41 man
drwxr-xr-x 75 jovyan jovyan 4.0K Aug  2 17:42 mkspecs
drwxr-xr-x  2 jovyan jovyan 4.0K Aug  2 17:42 phrasebooks
drwxr-xr-x  2 root   root   4.0K Aug  2 17:36 pkgs
drwxr-xr-x 30 jovyan jovyan 4.0K Aug  2 17:42 plugins
drwxr-xr-x 26 jovyan jovyan 4.0K Aug  2 17:42 qml
drwxr-xr-x  3 jovyan jovyan 4.0K Aug  2 17:42 qsci
drwxr-xr-x  2 jovyan jovyan 4.0K Aug  2 17:42 resources
drwxr-xr-x  2 jovyan jovyan 4.0K Aug  2 17:41 sbin
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  2 17:42 share
drwxr-xr-x  3 jovyan jovyan 4.0K Aug  1 19:13 shell
drwxr-xr-x  3 jovyan jovyan 4.0K Aug  1 19:13 ssl
drwxr-xr-x  3 jovyan jovyan  12K Aug  2 17:42 translations
drwxr-xr-x  3 jovyan jovyan 4.0K Aug  2 17:41 var
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  1 19:13 x86_64-conda_cos6-linux-gnu
drwxr-xr-x  1 jovyan jovyan 4.0K Aug  2 17:41 x86_64-conda-linux-gnu
```

**Pull request merged**
