### PR TITLE
Add biomod2

### PR DESCRIPTION
**Pull request by ocefpaf**
@abkfenris I'm creating a conda-forge package for this one in https://github.com/conda-forge/staged-recipes/pull/12368 but it may take a while. So let's add it via an R install b/c @SeascapeScience needs this for today's tutorial.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Argh. My `set -e` did not work .This actually failed :-/

```
2020-08-12T14:25:35.6941748Z [0m[91m* removing ‘/srv/conda/envs/notebook/lib/R/library/caret’
2020-08-12T14:25:36.0874308Z [0m[91mERROR: dependencies ‘pROC’, ‘nnet’, ‘gbm’, ‘mda’, ‘randomForest’, ‘rpart’, ‘dismo’, ‘caret’, ‘ENMeval’, ‘earth’, ‘checkmate’, ‘maxnet’ are not available for package ‘biomod2’
2020-08-12T14:25:36.0875886Z [0m[91m* removing ‘/srv/conda/envs/notebook/lib/R/library/biomod2’
```

**Comment by ocefpaf** [comment]
I'm focusing on https://github.com/conda-forge/staged-recipes/pull/12368 b/c there are many dependencies  here that required compilation that are failing. A conda package is probably easier at the moment.

**Comment by abkfenris** [comment]
I wonder if `Rscript` is always returning 0 for install steps.

**Comment by ocefpaf** [comment]
OK... that may not be the easiest way though:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=196444&view=logs&jobId=10bda42a-d420-5c28-a43f-bc4e66405e5c&j=10bda42a-d420-5c28-a43f-bc4e66405e5c&t=bef775d0-a1a2-55a3-9721-17147029baf0

@SeascapeScience there are many compiled parts on the dependencies and I'm having trouble creating a binary for `biomod2`. I heard that RStudiom the company, has Linux binaries now, do you know about those? Maybe we can use them here instead.

> I wonder if `Rscript` is always returning 0 for install steps.

We should wrap those install calls in another script anyway and force an exit code 1.

**Comment by abkfenris** [comment]
`breakItAll.R`

**Comment by abkfenris** [comment]
Ahh, we don't have to make our own script. We can add [`littler`](https://github.com/eddelbuettel/littler via Conda, then:

```
install.R -r https://cloud.r-project.org/ biomod2
installGithub.R BigelowLab/rasf BigelowLab/ohwobpg
```

**Pull request merged**
