### PR TITLE
test installing extra r pkgs

### PR DESCRIPTION
**Pull request by ocefpaf**
Fingers crossed!

### CODE REVIEW

**Comment by ocefpaf** [comment]
OK. This passed! Let's merge and create a new image.

@salvis2 can you refresh the hub later with the new image that has these changes?

**Comment by salvis2** [comment]
The hub should find the new image whenever someone logs in after the image is live!

**Comment by ocefpaf** [comment]
I thought we need to something in https://github.com/oceanhackweek/ohw-jupyterhub-2020  to make it pull the new image. I tested and it loaded the old one instead of the latest one in https://hub.docker.com/repository/docker/uwhackweeks/oceanhackweek/tags?page=1

PS: now the tag is latest instead of master :smile:
We probably need to revert that change I made, right?

**Comment by salvis2** [comment]
> I thought we need to something in https://github.com/oceanhackweek/ohw-jupyterhub-2020 to make it pull the new image. I tested and it loaded the old one instead of the latest one in https://hub.docker.com/repository/docker/uwhackweeks/oceanhackweek/tags?page=1
> 
> PS: now the tag is latest instead of master 😄
> We probably need to revert that change I made, right?

It currently references `latest`: https://github.com/oceanhackweek/ohw-jupyterhub-2020/blob/staging/deployments/ohw-hub/config/prod.yaml#L14 but I can confirm logging in as well that it does not have the new packages. Maybe we should just have manual tags, like `12727c6`. What do you think?

**Comment by ocefpaf** [comment]
> It currently references `latest`: [oceanhackweek/ohw-jupyterhub-2020@`staging`/deployments/ohw-hub/config/prod.yaml#L14](https://github.com/oceanhackweek/ohw-jupyterhub-2020/blob/staging/deployments/ohw-hub/config/prod.yaml?rgh-link-date=2020-08-06T00%3A18%3A34Z#L14)

Ah yes. Your commit fixed that.

> but I can confirm logging in as well that it does not have the new packages. Maybe we should just have manual tags, like `12727c6`. What do you think?

Whatever works. Not sure why we get both. Also, those are not "manual," right? I believe they get the sha from the commit, no? (Sorry for all these questions. It is a new workflow or me.)

**Comment by salvis2** [comment]
> Whatever works. Not sure why we get both. Also, those are not "manual," right? I believe they get the sha from the commit, no?

I think both of these are correct. I think ICESat-2 had GitHub actions to make new tags on DockerHub whenever we made a tag in the GitHub repo. Maybe just waiting a bit will make the JupyterHub realize there is a new image.

**Comment by ocefpaf** [comment]
> Maybe just waiting a bit will make the JupyterHub realize there is a new image.

Yep. That is the part I'm confused :smile:

**Comment by salvis2** [comment]
I'll check a few times tonight and see if it grabs the new image.

**Comment by salvis2** [comment]
Checked just now and I'm not seeing the new packages. Will switch to manual tags tomorrow.

**Comment by salvis2** [comment]
@ocefpaf it looks like the new packages are there now. Just took maybe a day for the hub to check and find the new image.

**Comment by ocefpaf** [comment]
Yep. Just tested them. Thanks!

R-debug

**Pull request merged**
