### PR TITLE
minor env change to test the image

### PR DESCRIPTION
**Pull request by ocefpaf**
@emiliom, @salvis2, and @leewujung I created the secrets and copied our image info here
Let's see if this works. Expecting to crash and burn :-)

PS: ideally we should have a separate repo that is why I moved away from the idea of having this in the tutorial one.

### CODE REVIEW

**Comment by emiliom** [comment]
:fire_engine: standing by

**Comment by salvis2** [comment]
Maybe you need this line from the ICESat-2 hackweek's `environment.yml`? 
https://github.com/ICESAT-2HackWeek/jupyter-image-2020/blob/4459b65fb89a5588fc51b4c429f58f8f01284dc8/environment.yml#L7

**Comment by emiliom** [comment]
>Maybe you need this line from the ICESat-2 hackweek's environment.yml
> https://github.com/ICESAT-2HackWeek/jupyter-image-2020/blob/4459b65fb89a5588fc51b4c429f58f8f01284dc8/environment.yml#L7
>
>If you will be using the pangeo-notebook base image.

That makes a lot of sense!

**Comment by ocefpaf** [comment]
> That makes a lot of sense!

If only [the guy who](https://github.com/conda-forge/staged-recipes/pull/10969) created that meta-package knew about it!

**Comment by ocefpaf** [comment]
Let's merge this and see if the secrets are working, it should upload the image to Dockerhub.

Thanks @salvis2 for all the help!

**Pull request merged**
